//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S1.L01C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S1.L01C.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Växelpengar - Nivå C.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för ny beräkning - Esc avslutar..
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; kan inte tolkas som en giltig summa pengar..
        /// </summary>
        internal static string Invalid_Value_Error {
            get {
                return ResourceManager.GetString("Invalid_Value_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; är inte en tillräckligt stor summa pengar..
        /// </summary>
        internal static string Low_Value_Error {
            get {
                return ResourceManager.GetString("Low_Value_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lappar.
        /// </summary>
        internal static string Notetype_Bills {
            get {
                return ResourceManager.GetString("Notetype_Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kronor.
        /// </summary>
        internal static string Notetype_Coins {
            get {
                return ResourceManager.GetString("Notetype_Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontant          :{0, 13:c0}.
        /// </summary>
        internal static string Reciept_Cash {
            get {
                return ResourceManager.GetString("Reciept_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka         :{0, 13:c0}.
        /// </summary>
        internal static string Reciept_Change {
            get {
                return ResourceManager.GetString("Reciept_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------.
        /// </summary>
        internal static string Reciept_Line {
            get {
                return ResourceManager.GetString("Reciept_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öresavrundning   :{0, 13:c}.
        /// </summary>
        internal static string Reciept_RoundingOffAmount {
            get {
                return ResourceManager.GetString("Reciept_RoundingOffAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVITTO.
        /// </summary>
        internal static string Reciept_String {
            get {
                return ResourceManager.GetString("Reciept_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt           :{0, 13:c}.
        /// </summary>
        internal static string Reciept_SubTotal {
            get {
                return ResourceManager.GetString("Reciept_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att betala       :{0, 13:c0}.
        /// </summary>
        internal static string Reciept_Total {
            get {
                return ResourceManager.GetString("Reciept_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange erhållet belopp: .
        /// </summary>
        internal static string Recieved_Prompt {
            get {
                return ResourceManager.GetString("Recieved_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange totalsumma     : .
        /// </summary>
        internal static string Total_Prompt {
            get {
                return ResourceManager.GetString("Total_Prompt", resourceCulture);
            }
        }
    }
}
